language: python
python:
  - "3.6"
  - "3.6-dev"  # 3.6 development branch
  - "3.7-dev"  # 3.7 development branch

# 3.7 requires "xenial", doesn't work with "trusty"
# see https://github.com/travis-ci/travis-ci/issues/9815
matrix:
  include:
    - python: 3.7
      dist: xenial
      sudo: true

before_install:
  - pip install poetry

# command to install dependencies
install:
  - make init

# command to run tests
script:
  - make bandit
  - make pycodestyle
  - make pylint-error

notifications:
  email:
    on_success: never
    on_failure: always

